# Generated by Django 4.2.5 on 2023-09-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='code',
            field=models.CharField(default='624881', editable=False, max_length=100),
        ),
    ]
