# Generated by Django 4.2.5 on 2023-11-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='capital',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='code',
            field=models.CharField(default='750860', editable=False, max_length=100),
        ),
    ]
