# Generated by Django 4.2.5 on 2023-10-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_passwordresetrequest_code_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='code',
            field=models.CharField(default='897976', editable=False, max_length=100),
        ),
    ]
