# Generated by Django 4.2.5 on 2023-10-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_passwordresetrequest_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='records.subject'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='code',
            field=models.CharField(default='179717', editable=False, max_length=100),
        ),
    ]
