# Generated by Django 4.2.5 on 2023-10-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_passwordresetrequest_code_alter_strand_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='code',
            field=models.CharField(default='606465', editable=False, max_length=100),
        ),
        migrations.RemoveField(
            model_name='strand',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='strand',
            name='curriculum',
            field=models.ManyToManyField(related_name='strands', to='records.curriculum'),
        ),
    ]
