# Generated by Django 4.2.5 on 2023-10-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_passwordresetrequest_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strand',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='substrand',
            name='curriculum',
            field=models.ManyToManyField(related_name='substrands', to='records.curriculum'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.CharField(choices=[('B4', 'B4'), ('B5', 'B5'), ('B6', 'B6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='code',
            field=models.CharField(default='204586', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='substrand',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
