# Generated by Django 4.2.5 on 2023-10-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_remove_strand_curriculum_substrand_curriculum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='code',
            field=models.CharField(default='863991', editable=False, max_length=100),
        ),
    ]
