# Generated by Django 4.2.5 on 2023-11-05 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('owner', models.CharField(choices=[('private', 'Private'), ('government', 'Government')], default='government', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('mixed', 'Mixed'), ('males', 'Males'), ('females', 'Females')], default='mixed', max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('digital_address', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.URLField(blank=True, help_text='School location on google map', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_established', models.DateField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True, help_text='Tick to show that the school is visible to users')),
                ('logo', models.ImageField(default='defaults/cover.jpeg', upload_to='school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school/images')),
                ('caption', models.CharField(max_length=225)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='school/feeds')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='schools.school')),
            ],
        ),
    ]
