# Generated by Django 4.2.5 on 2023-11-05 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.CharField(editable=False, max_length=100, unique=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.CharField(editable=False, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['subject__name', 'grade'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Grade name')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=1000)),
                ('annotation', models.CharField(editable=False, max_length=100, unique=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='curriculums.contentstandard', verbose_name='Content standard')),
            ],
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.CharField(editable=False, max_length=100, unique=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100, verbose_name='Strand name')),
                ('curriculums', models.ManyToManyField(related_name='strands', to='curriculums.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Subject name')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Substrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.CharField(editable=False, max_length=100, unique=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('curriculums', models.ManyToManyField(related_name='substrands', to='curriculums.curriculum')),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substrands', to='curriculums.strand')),
            ],
        ),
        migrations.AddField(
            model_name='strand',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='curriculums.subject'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.CharField(editable=False, max_length=100, unique=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('topic', models.CharField(max_length=1024)),
                ('content', models.TextField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculums.learningindicator')),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='curriculums.grade'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='curriculums.subject'),
        ),
        migrations.AddField(
            model_name='contentstandard',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_standards', to='curriculums.curriculum'),
        ),
        migrations.AddField(
            model_name='contentstandard',
            name='substrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_standards', to='curriculums.substrand'),
        ),
    ]
