# Generated by Django 4.2.5 on 2023-11-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_passwordresetrequest_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='code',
            field=models.CharField(default='269023', editable=False, max_length=100),
        ),
    ]
